name: htrace-image

on:
  push:
    branches:
      - "master"
  release:
    types:
      - "published"
  pull_request:
    branches: 
      - "master"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Publish dev image to container registry
    - name: build atlantis:dev image
      if: ${{ github.event_name == 'push'}}
      run: |
        make build-service
        docker build -t ghcr.io/deamwork/htrace.sh:dev .
    - name: publish atlantis:dev image
      if: ${{ github.event_name == 'push'}}
      run: |
        docker push ghcr.io/deamwork/htrace.sh:dev
    # Publish release to container registry
    - name: populate release version
      if: ${{ github.event_name == 'release'}}
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: build atlantis:$RELEASE_VERSION release image
      if: ${{ github.event_name == 'release'}}
      run: |
        make build-service
        docker build -t ghcr.io/deamwork/htrace.sh:$RELEASE_VERSION .
    - name: publish atlantis:$RELEASE_VERSION release image
      if: ${{ github.event_name == 'release'}}
      run: |
        docker push ghcr.io/deamwork/htrace.sh:$RELEASE_VERSION
        docker tag ghcr.io/deamwork/htrace.sh:$RELEASE_VERSION ghcr.io/deamwork/htrace.sh:latest
        docker push ghcr.io/deamwork/htrace.sh:latest
